In [49]:
import pandas as pd

In [50]:
cols_final = ['population',
 'racepctblack',
 'agePct12t29',
 'numbUrban',
 'medIncome',
 'pctWWage',
 'pctWInvInc',
 'medFamInc',
 'perCapInc',
 'whitePerCap',
 'PctEmploy',
 'MalePctDivorce',
 'MalePctNevMarr',
 'TotalPctDiv',
 'PctKids2Par',
 'PctWorkMom',
 'NumImmig',
 'PctRecImmig8',
 'PctRecImmig10',
 'PctLargHouseOccup',
 'PersPerOccupHous',
 'PersPerRentOccHous',
 'PctPersOwnOccup',
 'PctPersDenseHous',
 'HousVacant',
 'PctHousOwnOcc',
 'OwnOccLowQuart',
 'OwnOccMedVal',
 'RentLowQ',
 'RentMedian',
 'MedRent',
 'MedOwnCostPctIncNoMtg',
 'NumStreet']

In [51]:
# Read data

data = pd.read_csv("..\\Raw_Data\\CommViolPredUnnormalizedData.txt", sep='\s*,\s*',encoding='latin-1',engine='python',na_values=["?"]) # Ensure that unknown values are set to NA

data.columns = ['communityname','state','countyCode','communityCode','fold','population','householdsize','racepctblack',
           'racePctWhite','racePctAsian','racePctHisp','agePct12t21','agePct12t29','agePct16t24','agePct65up',
           'numbUrban','pctUrban','medIncome','pctWWage','pctWFarmSelf','pctWInvInc','pctWSocSec','pctWPubAsst',
           'pctWRetire','medFamInc','perCapInc','whitePerCap','blackPerCap','indianPerCap','AsianPerCap','OtherPerCap',
           'HispPerCap','NumUnderPov','PctPopUnderPov','PctLess9thGrade','PctNotHSGrad','PctBSorMore','PctUnemployed',
           'PctEmploy','PctEmplManu','PctEmplProfServ','PctOccupManu','PctOccupMgmtProf','MalePctDivorce',
           'MalePctNevMarr','FemalePctDiv','TotalPctDiv','PersPerFam','PctFam2Par','PctKids2Par','PctYoungKids2Par',
           'PctTeen2Par','PctWorkMomYoungKids','PctWorkMom','NumKidsBornNeverMar','PctKidsBornNeverMar','NumImmig',
           'PctImmigRecent','PctImmigRec5','PctImmigRec8','PctImmigRec10','PctRecentImmig','PctRecImmig5',
           'PctRecImmig8','PctRecImmig10','PctSpeakEnglOnly','PctNotSpeakEnglWell','PctLargHouseFam',
           'PctLargHouseOccup','PersPerOccupHous','PersPerOwnOccHous','PersPerRentOccHous','PctPersOwnOccup',
           'PctPersDenseHous','PctHousLess3BR','MedNumBR','HousVacant','PctHousOccup','PctHousOwnOcc','PctVacantBoarded',
           'PctVacMore6Mos','MedYrHousBuilt','PctHousNoPhone','PctWOFullPlumb','OwnOccLowQuart','OwnOccMedVal',
           'OwnOccHiQuart','OwnOccQrange','RentLowQ','RentMedian','RentHighQ','RentQrange','MedRent','MedRentPctHousInc',
           'MedOwnCostPctInc','MedOwnCostPctIncNoMtg','NumInShelters','NumStreet','PctForeignBorn','PctBornSameState',
           'PctSameHouse85','PctSameCity85','PctSameState85','LemasSwornFT','LemasSwFTPerPop','LemasSwFTFieldOps',
           'LemasSwFTFieldPerPop','LemasTotalReq','LemasTotReqPerPop','PolicReqPerOffic','PolicPerPop',
           'RacialMatchCommPol','PctPolicWhite','PctPolicBlack','PctPolicHisp','PctPolicAsian','PctPolicMinor',
           'OfficAssgnDrugUnits','NumKindsDrugsSeiz','PolicAveOTWorked','LandArea','PopDens','PctUsePubTrans',
           'PolicCars','PolicOperBudg','LemasPctPolicOnPatr','LemasGangUnitDeploy','LemasPctOfficDrugUn',
           'PolicBudgPerPop','murders','murdPerPop','rapes','rapesPerPop','robberies','robbbPerPop','assaults',
           'assaultPerPop','burglaries','burglPerPop','larcenies','larcPerPop','autoTheft','autoTheftPerPop','arsons',
           'arsonsPerPop','ViolentCrimesPerPop','nonViolPerPop']

In [52]:
## For the few columns where there are only small amounts of NA values, just delete these rows

data = data[data['ViolentCrimesPerPop'].notna()]

In [53]:
## remove the rows with < 1000 na values and naming variables (such as community name for example)
columns_to_drop = ['communityCode', 'countyCode', 'LemasSwornFT', 'LemasSwFTPerPop', 'LemasSwFTFieldOps', 'LemasSwFTFieldPerPop',
                   'LemasTotalReq', 'LemasTotReqPerPop', 'PolicReqPerOffic', 'PolicPerPop', 'RacialMatchCommPol', 'PctPolicWhite',
                  'PctPolicBlack', 'PctPolicHisp', 'PctPolicAsian', 'OfficAssgnDrugUnits', 'NumKindsDrugsSeiz', 'PolicAveOTWorked',
                  'PolicCars', 'PolicOperBudg', 'LemasPctPolicOnPatr', 'LemasGangUnitDeploy', 'PolicBudgPerPop', 'arsons', 'arsonsPerPop',
                  'nonViolPerPop', 'PctPolicMinor', 'communityname', 'state', 'fold']
data = data.drop(columns_to_drop, axis=1)

In [54]:
data.isnull().sum()

population             0
householdsize          0
racepctblack           0
racePctWhite           0
racePctAsian           0
                      ..
larcenies              2
larcPerPop             2
autoTheft              3
autoTheftPerPop        3
ViolentCrimesPerPop    0
Length: 117, dtype: int64

In [55]:
data.head()

,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,...,robbbPerPop,assaults,assaultPerPop,burglaries,burglPerPop,larcenies,larcPerPop,autoTheft,autoTheftPerPop,ViolentCrimesPerPop
0,23123,2.82,0.80,95.57,3.44,0.85,11.01,21.30,10.48,17.18,...,21.26,24.0,102.05,57.0,242.37,376.0,1598.78,26.0,110.55,127.56
1,29344,2.43,0.74,94.33,3.43,2.35,11.36,25.88,11.01,10.28,...,154.95,14.0,38.74,274.0,758.14,1797.0,4972.19,136.0,376.30,218.59
2,16656,2.40,1.70,97.35,0.50,0.70,12.55,25.20,12.19,17.57,...,57.86,33.0,190.93,225.0,1301.78,716.0,4142.56,47.0,271.93,306.64
4,140494,2.45,2.51,95.65,0.90,0.95,18.09,32.89,20.04,13.26,...,90.05,449.0,297.29,2094.0,1386.46,7690.0,5091.64,454.0,300.60,442.95
5,28700,2.60,1.60,96.57,1.47,1.10,11.17,27.41,12.76,14.42,...,30.44,54.0,182.66,110.0,372.09,288.0,974.19,144.0,487.10,226.63

In [56]:


# Removing the predictor variables
pred = ['robbbPerPop', 'assaults', 'assaultPerPop', 'burglaries', 
        'burglPerPop', 'larcenies', 'larcPerPop', 'autoTheft', 
       'autoTheftPerPop', 'murdPerPop', 'rapes', 'rapesPerPop', 'robberies']
data = data.drop(pred, axis=1)

In [57]:
#Creating a new column for high crimes
def high_crime(row):
    if row['ViolentCrimesPerPop'] > 3000:
        return 1
    elif row['ViolentCrimesPerPop'] < 3000:
        return 0
    
    
data['HighCrime'] = data.apply(high_crime, axis = 1)
#also drop the violent crimes per pop line
data = data.drop(['ViolentCrimesPerPop'], axis = 1)

In [68]:
import os 
output_path = os.path.dirname(os.getcwd())
file = 'cleaned_data.csv'
path = os.path.join(output_path, file)
print(path)

D:\OneDrive - University College London\UCL\CEGE0004\CEGE0004\cleaned_data.csv

In [81]:
#import csv to check 
columns = 'population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,numbUrban,pctUrban,medIncome,pctWWage,pctWFarmSelf,pctWInvInc,pctWSocSec,pctWPubAsst,pctWRetire,medFamInc,perCapInc,whitePerCap,blackPerCap,indianPerCap,AsianPerCap,OtherPerCap,HispPerCap,NumUnderPov,PctPopUnderPov,PctLess9thGrade,PctNotHSGrad,PctBSorMore,PctUnemployed,PctEmploy,PctEmplManu,PctEmplProfServ,PctOccupManu,PctOccupMgmtProf,MalePctDivorce,MalePctNevMarr,FemalePctDiv,TotalPctDiv,PersPerFam,PctFam2Par,PctKids2Par,PctYoungKids2Par,PctTeen2Par,PctWorkMomYoungKids,PctWorkMom,NumKidsBornNeverMar,PctKidsBornNeverMar,NumImmig,PctImmigRecent,PctImmigRec5,PctImmigRec8,PctImmigRec10,PctRecentImmig,PctRecImmig5,PctRecImmig8,PctRecImmig10,PctSpeakEnglOnly,PctNotSpeakEnglWell,PctLargHouseFam,PctLargHouseOccup,PersPerOccupHous,PersPerOwnOccHous,PersPerRentOccHous,PctPersOwnOccup,PctPersDenseHous,PctHousLess3BR,MedNumBR,HousVacant,PctHousOccup,PctHousOwnOcc,PctVacantBoarded,PctVacMore6Mos,MedYrHousBuilt,PctHousNoPhone,PctWOFullPlumb,OwnOccLowQuart,OwnOccMedVal,OwnOccHiQuart,OwnOccQrange,RentLowQ,RentMedian,RentHighQ,RentQrange,MedRent,MedRentPctHousInc,MedOwnCostPctInc,MedOwnCostPctIncNoMtg,NumInShelters,NumStreet,PctForeignBorn,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn,murders,HighCrime'
test = columns.split(',')

data = pd.read_csv(path)
df = pd.DataFrame(data, columns=test)

,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,...,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn,murders,HighCrime
0,23123,2.82,0.80,95.57,3.44,0.85,11.01,21.30,10.48,17.18,...,77.17,71.27,90.22,96.12,10.6,2186.7,3.84,0.0,0,0
1,29344,2.43,0.74,94.33,3.43,2.35,11.36,25.88,11.01,10.28,...,44.77,36.60,61.26,82.85,10.6,2780.9,4.37,0.0,3,0
2,16656,2.40,1.70,97.35,0.50,0.70,12.55,25.20,12.19,17.57,...,88.71,56.70,90.17,96.24,5.2,3217.7,3.31,0.0,0,0
3,140494,2.45,2.51,95.65,0.90,0.95,18.09,32.89,20.04,13.26,...,64.35,42.29,70.61,85.66,70.4,1995.7,0.97,0.0,7,0
4,28700,2.60,1.60,96.57,1.47,1.10,11.17,27.41,12.76,14.42,...,77.30,63.45,82.23,93.53,10.9,2643.5,9.62,0.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1988,56216,3.07,6.87,61.68,15.23,29.86,15.46,30.16,14.34,8.08,...,52.67,39.19,74.58,85.88,16.7,3365.4,0.59,0.0,10,0
1989,12251,2.68,21.18,76.65,1.52,1.29,17.36,31.23,16.97,12.57,...,75.16,49.12,78.79,92.85,7.3,1682.8,1.15,0.0,0,0
1990,32824,2.46,0.52,92.62,0.98,11.00,11.81,20.96,9.53,20.73,...,48.66,46.73,75.54,92.30,27.5,1195.2,0.12,0.0,5,0
1991,13547,2.89,3.37,69.91,0.90,62.11,17.16,30.01,14.73,10.42,...,82.26,54.05,79.72,94.06,6.3,2142.2,0.00,0.0,0,0
1992,28898,2.61,2.39,71.27,9.09,24.43,12.99,25.21,11.63,12.12,...,55.29,48.74,66.20,89.08,21.7,1331.0,1.39,0.0,5,0