In [2]:
import os 
import pandas as pd
output_path = os.path.dirname(os.getcwd())
file = 'cleaned_data.csv'
path = os.path.join(output_path, file)

#import csv to check 
columns = 'population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,numbUrban,pctUrban,medIncome,pctWWage,pctWFarmSelf,pctWInvInc,pctWSocSec,pctWPubAsst,pctWRetire,medFamInc,perCapInc,whitePerCap,blackPerCap,indianPerCap,AsianPerCap,OtherPerCap,HispPerCap,NumUnderPov,PctPopUnderPov,PctLess9thGrade,PctNotHSGrad,PctBSorMore,PctUnemployed,PctEmploy,PctEmplManu,PctEmplProfServ,PctOccupManu,PctOccupMgmtProf,MalePctDivorce,MalePctNevMarr,FemalePctDiv,TotalPctDiv,PersPerFam,PctFam2Par,PctKids2Par,PctYoungKids2Par,PctTeen2Par,PctWorkMomYoungKids,PctWorkMom,NumKidsBornNeverMar,PctKidsBornNeverMar,NumImmig,PctImmigRecent,PctImmigRec5,PctImmigRec8,PctImmigRec10,PctRecentImmig,PctRecImmig5,PctRecImmig8,PctRecImmig10,PctSpeakEnglOnly,PctNotSpeakEnglWell,PctLargHouseFam,PctLargHouseOccup,PersPerOccupHous,PersPerOwnOccHous,PersPerRentOccHous,PctPersOwnOccup,PctPersDenseHous,PctHousLess3BR,MedNumBR,HousVacant,PctHousOccup,PctHousOwnOcc,PctVacantBoarded,PctVacMore6Mos,MedYrHousBuilt,PctHousNoPhone,PctWOFullPlumb,OwnOccLowQuart,OwnOccMedVal,OwnOccHiQuart,OwnOccQrange,RentLowQ,RentMedian,RentHighQ,RentQrange,MedRent,MedRentPctHousInc,MedOwnCostPctInc,MedOwnCostPctIncNoMtg,NumInShelters,NumStreet,PctForeignBorn,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn,murders,HighCrime'
test = columns.split(',')

data = pd.read_csv(path)
df = pd.DataFrame(data, columns=test)
df.head()

,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,...,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn,murders,HighCrime
0,23123,2.82,0.80,95.57,3.44,0.85,11.01,21.30,10.48,17.18,...,77.17,71.27,90.22,96.12,10.6,2186.7,3.84,0.0,0,0
1,29344,2.43,0.74,94.33,3.43,2.35,11.36,25.88,11.01,10.28,...,44.77,36.60,61.26,82.85,10.6,2780.9,4.37,0.0,3,0
2,16656,2.40,1.70,97.35,0.50,0.70,12.55,25.20,12.19,17.57,...,88.71,56.70,90.17,96.24,5.2,3217.7,3.31,0.0,0,0
3,140494,2.45,2.51,95.65,0.90,0.95,18.09,32.89,20.04,13.26,...,64.35,42.29,70.61,85.66,70.4,1995.7,0.97,0.0,7,0
4,28700,2.60,1.60,96.57,1.47,1.10,11.17,27.41,12.76,14.42,...,77.30,63.45,82.23,93.53,10.9,2643.5,9.62,0.0,0,0